#ifndef CONSTANT_H_
#define CONSTANT_H_

#define MEMORY_SIZE 4096
#define PIXEL_SIZE 16
#define REFRESH_RATE 60
#define DELAY 1000 / REFRESH_RATE
#define DISPLAY_WIDTH 64
#define DISPLAY_HEIGHT 32

#define FOREGROUND_COLOR 255, 255, 255
#define BACKGROUND_COLOR 0, 0, 0

#define TONE 440

#endif // CONSTANT_H_